# Generated by Django 3.1.7 on 2021-11-08 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_squashed_0038_auto_20210921_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end_point',
            name='end_point_type',
            field=models.CharField(choices=[('d', 'dcat'), ('a', 'arc_gis_rest'), ('c', 'CONTENTdm'), ('ds', 'dspace'), ('co', 'codex')], default='a', max_length=2),
        ),
        migrations.AlterField(
            model_name='resource',
            name='format',
            field=models.ForeignKey(blank=True, help_text='The format of the data. E.g Shapefile, GeoTIFF, JPEG, TIFF, ArcGRID, Paper Map, Geodatabase, E00 Cartographic Material, ESRI Geodatabase, SQLite Database, GeoJSON, Raster Dataset, Scanned Map, etc. Used in Facet search', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.format'),
        ),
    ]
