# Generated by Django 3.1.7 on 2021-12-06 22:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20211108_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='end_point',
            name='disclaimer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
