# Generated by Django 3.1.7 on 2022-01-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_end_point_disclaimer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='category_keywords',
            options={'verbose_name_plural': 'category_keywords'},
        ),
        migrations.AddField(
            model_name='url_type',
            name='ref',
            field=models.CharField(blank=True, help_text='The standard for the URL', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='url_type',
            name='service',
            field=models.BooleanField(blank=True, help_text='If the url has mappability.', null=True),
        ),
        migrations.AlterField(
            model_name='end_point',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.publisher'),
        ),
    ]
