# Generated by Django 3.1.7 on 2022-01-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_populate_url_refs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url_type',
            options={'verbose_name_plural': 'URL Types'},
        ),
        migrations.AlterField(
            model_name='url_type',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
