# Generated by Django 3.1.7 on 2022-03-30 15:48

from django.db import migrations, models
import json

from pathlib import Path


DATA_FILENAME = 'gbl_resource.json'
def load_data(apps, schema_editor):
    Resource_Type = apps.get_model('resources', 'Resource_Type')

    # access file level one above current
    jsonfile = Path(__file__).parents[1] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        # we're going to populate the table in 3 steps

        # 1) generate the categories
        for obj in objects:
            print(obj['name'])
            Resource_Type(name=obj['name']).save()



def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    # todo empty the database tables
    print("Reversed!")

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20220120_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ManyToManyField(blank=True, to='resources.Resource_Type'),
        ),
        migrations.RunPython(load_data, reverse_func)
    ]
