# Generated by Django 3.1.7 on 2022-03-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20220330_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='parent',
        ),
        migrations.AddField(
            model_name='resource',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_resource_parent_+', to='resources.Resource'),
        ),
    ]
