# Generated by Django 3.1.7 on 2022-04-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_resource_missing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Named_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='place',
        ),
        migrations.AddField(
            model_name='resource',
            name='named_place',
            field=models.ManyToManyField(blank=True, to='resources.Named_Place'),
        ),
    ]
