# Generated by Django 3.1.7 on 2022-04-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_auto_20220415_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
